vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        article_pictures:
            uri_prefix: '%article_pictures%'
            upload_destination: '%kernel.project_dir%/public/%article_pictures%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
